[tools]
node = 'lts'
java = "zulu-17.42.19"
usage = "latest"
maven = "3"
bun = "latest"
pnpm = "latest"
gh = "latest"
awscli = "latest"
pipx = "latest"
jq = "latest"
yq = "latest"
python = "3.13"
claude = "latest"
"npm:@zed-industries/claude-code-acp" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:mcp-hub" = "latest"
"npm:@github/copilot" = "latest"
"npm:typescript" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
